### PR TITLE
Remove unnecessary setup requirements

### PR DESCRIPTION
**Pull request by andersy005**
I realize that some unnecessary requirements were defined in `setup.py`: `setup_requires=['pytest>=3.0.0', 'pytest-runner']`. This PR removes these requirements.

### CODE REVIEW

**Comment by bmabey** [comment]
This [breaks the build](https://travis-ci.org/github/bmabey/provenance/builds/690282514?utm_source=github_status&utm_medium=notification) since it can no longer find `pytest` to run the tests.

**Comment by andersy005** [comment]
> This [breaks the build](https://travis-ci.org/github/bmabey/provenance/builds/690282514?utm_source=github_status&utm_medium=notification) since it can no longer find `pytest` to run the tests.

Per `pytest-runner` documentation, 

> pytest-runner depends on deprecated features of setuptools and relies on features that break security mechanisms in pip. For example ‘setup_requires’ and ‘tests_require’ bypass pip --require-hashes. 

So, I removed both the `setup_requires` and `test_require` options -- which is the recommendation from [`pytest-runner`'s README](https://github.com/pytest-dev/pytest-runner/#deprecation-notice) -- and updated the travis script to use pytest instead of 	`python setup.py test`.

**Comment by bmabey** [comment]
Got it, thanks!

**Comment by andersy005** [comment]
👍 You are welcome!

**Pull request merged**
