### PR TITLE
adds auto db migration and, optionally, db creation. Resolves #4

### LINKED ISSUE #4: add way for library users to easily migrate existing DBs

### PR DESCRIPTION
**Pull request by bmabey**
Before merging this in I want to make sure the user can specify a schema on the connection string or, if not, pass the schema in as a parameter to the repo.

### CODE REVIEW

**Comment by bmabey** [comment]
With this PR only the creation of a DB and schema is working, updating (i.e. migrating) a DB is not working yet so I've not added that parameter for now.

Existing provenance databases not created with this approach will be lacking the alembic version information and so won't be eligible for automatic migrations until that is fixed in each DB. To add the alembic version in existing DBs the alembic stamp command would need to be run on it as done [here](https://github.com/bmabey/provenance/blob/autodb/provenance/repos.py#L656-L657). /cc @mmb90

**Comment by scizo** [comment]
I think it is probably best to not auto migrate but have it be explicitly done. I can't imagine that it will happen too often, so it shouldn't be a very big burden to have to run a command. I think having them explicitly do it will give a user the opportunity to assess whether they have code that is running an older version that may be backwards incompatible with the schema changes.

**Comment by bmabey** [comment]
@scizo Yeah, I think you are right. I've added a new issue about the db migrations, see #25. When that gets done lets make it explicit.

**Comment by mmb90** [comment]
@bmabey, trying to run my basic-example with the new `create_db: True` option in the config. I get 
```
File "/Users/mattburbidge/anaconda3/envs/provenance-dev/lib/python3.5/site-packages/provenance-0.9.3+10.g3989735-py3.5.egg/provenance/_config.py", line 62, in items_from_config
    store = atomic_from_config(c, name=k)
  File "/Users/mattburbidge/anaconda3/envs/provenance-dev/lib/python3.5/site-packages/provenance-0.9.3+10.g3989735-py3.5.egg/provenance/_config.py", line 112, in from_config
    return repo_from_config(atomic_config)
  File "/Users/mattburbidge/anaconda3/envs/provenance-dev/lib/python3.5/site-packages/toolz-0.8.2-py3.5.egg/toolz/functoolz.py", line 283, in __call__
    return self._partial(*args, **kwargs)
  File "/Users/mattburbidge/anaconda3/envs/provenance-dev/lib/python3.5/site-packages/provenance-0.9.3+10.g3989735-py3.5.egg/provenance/_config.py", line 34, in atomic_item_from_config
    return cls(**kargs)
  File "/Users/mattburbidge/anaconda3/envs/provenance-dev/lib/python3.5/site-packages/provenance-0.9.3+10.g3989735-py3.5.egg/provenance/repos.py", line 600, in __init__
    self._db_init()
  File "/Users/mattburbidge/anaconda3/envs/provenance-dev/lib/python3.5/site-packages/provenance-0.9.3+10.g3989735-py3.5.egg/provenance/repos.py", line 657, in _db_init
    command.stamp(cfg, "head")
  File "/Users/mattburbidge/anaconda3/envs/provenance-dev/lib/python3.5/site-packages/alembic/command.py", line 336, in stamp
    script = ScriptDirectory.from_config(config)
  File "/Users/mattburbidge/anaconda3/envs/provenance-dev/lib/python3.5/site-packages/alembic/script/base.py", line 129, in from_config
    version_locations=version_locations
  File "/Users/mattburbidge/anaconda3/envs/provenance-dev/lib/python3.5/site-packages/alembic/script/base.py", line 57, in __init__
    "scripts folder." % dir)
alembic.util.exc.CommandError: Path doesn't exist: '/Users/mattburbidge/anaconda3/envs/provenance-dev/lib/python3.5/site-packages/provenance-0.9.3+10.g3989735-py3.5.egg/provenance/migrations'.  Please use the 'init' command to create a new scripts folder.
```
Should I need to run some sort of `alembic init ` before being able run run `basic_example.py`?

**Comment by bmabey** [comment]
@mmb90 No... It should just work.. I think the problem is that the migrations dir wasn't included in the package for some reason. I updated the `MANIFEST.in` to address this and it looks like it is being packaged now. Will you give it another try?

**Comment by mmb90** [comment]
Pulled the update. I can see that I have the migrations dir now. Problem persists with the same stack trace. The database is created and the blobs are in the blobstore but the artifacts don't make it into the db.

**Comment by bmabey** [comment]
Hrrmm... the tests pass just fine so it must be something with the packaging. @scizo, do you have any thoughts on what be wrong?

**Comment by scizo** [comment]
@mmb90 I just the basic example without an existing database. It successfully created the database, populated the database with tables, created the blobs, and saved the artifact to the database.

I did one thing differently, which may be a part of the problem. Instead of using the provided example environment, which pulls provenance from pypi, I created a symlink from the top level provenance directory into the basic example folder. That way you can ensure that the example is always being run with the checked out version of the code. I was using the provenance-dev environment, which after being created, in order for it to be complete you need to run `pip install -r requirements.txt` and `pip install -r test_requirements.txt`. 

Give it a try that way and let's see what happens.

**Comment by mmb90** [comment]
What I did:
1. Clone a fresh copy of bmabey/provenance
2. Create and activate fresh provenance-dev conda env
3. pip install requirements and test_requirements
4. cd examples/basic, remove environment.yml, ln -s ../../provenance provenance

Then it worked...chalk up another one for user error.

**Comment by scizo** [comment]
We should probably commit that link inside of the basic example then, and also put instructions how to use the provenance-dev environment correctly in the top level README, with a reference to it in the basic example README.

**Comment by mmb90** [comment]
I can update the examples and attach it to #22

**Comment by scizo** [comment]
Sounds great @mmb90. I just added a `Development` section to the main README that you can reference if you need to.

**Comment by bmabey** [comment]
The symlink approach tests the library but not the packaging. You could set the env to install from Github that would test both.

**Comment by mmb90** [comment]
@bmabey I may have been confused when I said I can see the migrations directory after you changed the manifest. Using the link method suggested by @scizo I'm able to run my examples just fine. Switching to your suggested method of having the env install from Github I'm having the same problem as before. Provenance gets installed at `~/anaconda3/envs/provenance-basic-example/lib/python3.5/site-packages/provenance/` and when you run `ls` on that dir there is no `migrations` dir. However there is a migrations dir in my local copy that I was creating a link to. I think there might still be something amiss here, maybe it's in my understanding of what should be happening though.

**Comment by bmabey** [comment]
Yeah, I think we still have a packaging issue. I'm not sure what magical incantation I need to add to the `MANIFEST.in` file but I'm pretty sure that is where the problem is.

**Comment by mmb90** [comment]
Perhaps it's this.

>In order for these files to be copied at install time to the package’s folder inside site-packages, you’ll need to supply `include_package_data=True` to the `setup()` function.

From [here](http://python-packaging.readthedocs.io/en/latest/non-code-files.html)

**Comment by scizo** [comment]
Installing from github will only work if the latest version on github is the code you are actually trying to test. It seems there will still be instances when github still doesn't reflect the changes you are trying to test.

**Comment by bmabey** [comment]
@mmb90 I added the `alembic.ini` which may have been the missing piece. It is pushed to github master so try the basic example again.

**Comment by mmb90** [comment]
ok check out #26. It works with those changes.

**Pull request merged**
