### PR TITLE
Getting Back to Working Build

### PR DESCRIPTION
**Pull request by dmaljovec**
This PR is a first pass at getting back to a working build so the CI can help vet new PRs for minimal correctness. Most of the changes here are configuration based (changing dependencies and their versions). Where code changes were necessary, I did my best to put a minimal footprint on the code, and I believe again the changes reflect only the minimal changes needed to accept new contracts from the dependent libraries. The integrity of the core logic should remain nearly untouched.

Builds off of #53.

### CODE REVIEW

**Comment by bmabey** [comment]
@dmaljovec will you rebase this branch and we can merge it in?

**Comment by dmaljovec** [comment]
Is it possible there is a non-deterministic test failure in here due to hypothesis?

```
tests/provenance/test_repos.py::test_permissions[memoryrepodbrepo-diskstore] FAILED [ 93%]
```

I am unable to trigger a Travis rebuild, but I see a few other tests fail *some* of the time locally:

```
tests/provenance/test_repos.py::test_permissions[dbrepo-memorystore] FAILED
tests/provenance/test_core.py::test_lazy_proxy_dict_allows_for_grouping_of_artifacts_of_same_name[chained-memmem] FAILED
```

That said, I can get *all* of them to pass *some* of the time. If it is okay with you, I would like to get this in, and then we can worry about the hypothesis failures on another PR? I can run the test suite locally a bunch of times and get some statistics like on our internal project a little while back to see which failures are more relevant, and hopefully we can work through those with some alacrity. Thoughts?

**Comment by dmaljovec** [comment]
> @dmaljovec will you rebase this branch and we can merge it in?

I am bad at rebasing (had a traumatizing experience once and have been too scared to try it again), did you just want the conflict resolved? I did merge master into this branch and resolved the subsequent conflicts. Let me know if you prefer that I clean up the commit history.

**Comment by bmabey** [comment]
I resolved the conflicts and merged this in locally.

**Pull request closed without merging**
